spring.application.name=demo05
spring.devtools.restart.additional-paths=src/main/resources
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=false

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/laboratorio_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
